<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/**
 * Class MenuResource
 * @package App\Http\Resources
 *  Template
[
"id"          => "string", // will be autogenerated if omitted
"text"        => "string", // node text
"icon"        => "string", // string for custom
"state"       => [
"opened"    => true , // is the node open
"disabled"  => false,  // is the node disabled
"selected"  => false,  // is the node selected
],
"children"    => [],  // array of strings or objects
"li_attr"     => [],  // attributes for the generated LI node
"a_attr"      => [],  // attributes for the generated A node
]
 */
class BackendMenuResource extends JsonResource
{

    public function __construct($resource)
    {
        static::$wrap = null;
        $this->resource = $resource;
    }
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'text' => $this->setName(),
            'icon' => $this->icon ?? 'far fa-file',
            'state'=>[
                'opened'=>0,
                'disabled'=>0,//(!$this->parent_id) ? 1 : 0,
                'selected'=>1,
            ],
            'children'=> BackendMenuResource::collection($this->children),
            'li_attr'=>['class'=>(!$this->parent_id) ? 'root': ''],
            'button_controls'=>[
                'data-edit'=>route('admin.backend_menu.edit',$this->id),
                'data-active'=>route('admin.backend_menu.active',$this->id),
                'data-delete'=>route('admin.backend_menu.destroy',$this->id),
            ],
            'a_attr'=>[
                'active'=>$this->active,
            ]
        ];
    }

    protected function setName()
    {
        if(isset($this->permission)){
            return $this->name ?? $this->permission->slug;
        }else{
            return $this->name ?? $this->type;
        }

//        if(isset($this->permission)){
//
//
//            $action = \Str::afterLast($this->permission->slug,'.');
//            dump($action);
//            dump($this->name);
////            dd($this->name);
////            if($action == 'index' ){
////                return "<a href='#'>".__($this->name)."</a> ";
////            }
//
//        }else{
//
//        }
    }
}
